language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
env:
  - FLASK=0.11.1
  - FLASK=0.10.1
  - FLASK=0.9
  - FLASK=0.8.1
matrix:
  exclude:
    - python: "3.3"
      env: FLASK=0.9
    - python: "3.3"
      env: FLASK=0.8.1
    - python: "3.4"
      env: FLASK=0.9
    - python: "3.4"
      env: FLASK=0.8.1
    - python: "3.5"
      env: FLASK=0.9
    - python: "3.5"
      env: FLASK=0.8.1
install:
  - pip install flask==$FLASK coverage
script:
- python tests.py
after_success: coveralls
