language: python
python:
  - "3.5"
  
install:
  - pip install -r requirements.txt
  
script:
  - nosetests
  - nosetests --with-coverage
  - nosetests --cover-package=forms
  - nosetests --cover-package=models
  - nosetests --cover-package=app
  - nosetests --cover-package=utils
  - coveralls

after_sucess:
  - "coveralls"

