language: python
python:
  - "3.5"
  
install:
  - pip install -r requirements.txt
  
script:
  - nosetests
  - nosetests --with-coverage --cover-package=forms/ models/ app utils
  - coveralls

after_sucess:
  - "coveralls"

