language: python
python:
  - "3.6"
  
install:
  - pip install -r requirements.txt
  
script:
  - nosetests
  - nosetests --with-coverage --cover-package=forms/
  - nosetests --with-coverage --cover-package=models/
  - nosetests --with-coverage --cover-package=app
  - nosetests --with-coverage --cover-package=utils
  - coveralls

after_sucess:
  - "coveralls"

